/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountBanner: typeof import('./src/components/trading/AccountBanner.vue')['default']
    AccountTabs: typeof import('./src/components/trading/AccountTabs.vue')['default']
    AgentCard: typeof import('./src/components/agent/AgentCard.vue')['default']
    ApprovalQueue: typeof import('./src/components/trading/ApprovalQueue.vue')['default']
    CapitalFlowChart: typeof import('./src/components/charts/CapitalFlowChart.vue')['default']
    DebatePanel: typeof import('./src/components/agent/DebatePanel.vue')['default']
    DebateTimeline: typeof import('./src/components/agent/DebateTimeline.vue')['default']
    DecisionCard: typeof import('./src/components/agent/DecisionCard.vue')['default']
    DrawdownChart: typeof import('./src/components/charts/DrawdownChart.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    EquityCurve: typeof import('./src/components/charts/EquityCurve.vue')['default']
    EvidenceTag: typeof import('./src/components/agent/EvidenceTag.vue')['default']
    ExtremeScenarioPie: typeof import('./src/components/charts/ExtremeScenarioPie.vue')['default']
    HiddenVariableMatrix: typeof import('./src/components/charts/HiddenVariableMatrix.vue')['default']
    InflectionTimeline: typeof import('./src/components/charts/InflectionTimeline.vue')['default']
    MarketChart: typeof import('./src/components/charts/MarketChart.vue')['default']
    ModelContribution: typeof import('./src/components/charts/ModelContribution.vue')['default']
    NewsFeed: typeof import('./src/components/common/NewsFeed.vue')['default']
    OrderList: typeof import('./src/components/trading/OrderList.vue')['default']
    PositionTable: typeof import('./src/components/trading/PositionTable.vue')['default']
    RiskRadar: typeof import('./src/components/charts/RiskRadar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectorHeatmap: typeof import('./src/components/charts/SectorHeatmap.vue')['default']
    SentimentChart: typeof import('./src/components/charts/SentimentChart.vue')['default']
    StatusBar: typeof import('./src/components/common/StatusBar.vue')['default']
    TradeHistory: typeof import('./src/components/trading/TradeHistory.vue')['default']
  }
}
