/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentCard: typeof import('./src/components/agent/AgentCard.vue')['default']
    CapitalFlowChart: typeof import('./src/components/charts/CapitalFlowChart.vue')['default']
    DebatePanel: typeof import('./src/components/agent/DebatePanel.vue')['default']
    DebateTimeline: typeof import('./src/components/agent/DebateTimeline.vue')['default']
    DecisionCard: typeof import('./src/components/agent/DecisionCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    EvidenceTag: typeof import('./src/components/agent/EvidenceTag.vue')['default']
    MarketChart: typeof import('./src/components/charts/MarketChart.vue')['default']
    NewsFeed: typeof import('./src/components/common/NewsFeed.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectorHeatmap: typeof import('./src/components/charts/SectorHeatmap.vue')['default']
    StatusBar: typeof import('./src/components/common/StatusBar.vue')['default']
  }
}
