/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CapitalFlowChart: typeof import('./src/components/charts/CapitalFlowChart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    MarketChart: typeof import('./src/components/charts/MarketChart.vue')['default']
    NewsFeed: typeof import('./src/components/common/NewsFeed.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectorHeatmap: typeof import('./src/components/charts/SectorHeatmap.vue')['default']
    StatusBar: typeof import('./src/components/common/StatusBar.vue')['default']
  }
}
