"""Portfolio-level validation for the 520 rule (preregistered, deterministic).

Locked by `docs/research/yeren-system/m3-520-portfolio-validation-
preregistration-2026-08-22.md`. The rule semantics, gating, and price
conventions are candidate E's, reused verbatim; this module adds only the
capital layer: 10% total-exposure cap (owner-authorized cross-card
citation), 5 concurrent slots x 2% each (researcher-added), 1,000,000 CNY
initial capital, actual broker fees (commission 0.015% with a 5 CNY floor).

The trade stream is generated by the very same `simulate_trades_e` that
produced the published candidate-E results, so the portfolio layer can only
decide which mechanical signals to take -- never when, or at what price.
Sizing and affordability are settled at each fill (the only moment the true
fill price exists); slot / duplicate / exposure checks run at the decision
close using that day's marks. Everything is a deterministic replay: no
random numbers, no seeds.

Research-only. No playbook, simulator order, broker instruction, or
execution service is created. `real_broker_orders=False` always.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from scripts.yeren_research.m3_520 import RuleSpec, compute_features
from scripts.yeren_research.m3_520_candidate_e import (
    MAX_PREFETCH_REFINE_PASSES,
    PREREGISTERED_END_DATE,
    PREREGISTERED_SPLIT_DATE,
    PREREGISTERED_START_DATE,
    PREREGISTERED_STOP_DAYS,
    CostModel,
    TradeE,
    _touched_dates_with_buffer,
    build_st_mask,
    build_universe,
    load_constraints,
    load_st_timeline,
    simulate_trades_e,
)
from scripts.yeren_research.market import load_trade_dates
from scripts.yeren_research.pit_priced_panel import PricedSeries, load_priced_panel

PREREGISTRATION = (
    "docs/research/yeren-system/"
    "m3-520-portfolio-validation-preregistration-2026-08-22.md"
)
OUTPUT_PATH = Path(
    "data/yeren_research/inventory/m3-520-portfolio-validation-2026-08-22.json"
)
TRADING_DAYS_PER_YEAR = 243
# Float drift tolerance for the exposure-cap comparison: five 2% slots land
# exactly on 10% by construction, and binary rounding must not spuriously
# reject the fifth slot.
EXPOSURE_TOLERANCE = 1e-6


@dataclass(frozen=True)
class PortfolioConfig:
    """Preregistered section-2 capital layer. Tests may shrink the numbers;
    the defaults are the locked values."""

    initial_capital: float = 1_000_000.0
    total_exposure_cap: float = 0.10
    max_positions: int = 5
    position_fraction: float = 0.02
    trading_days_per_year: int = TRADING_DAYS_PER_YEAR


@dataclass
class _OpenPosition:
    code: str
    shares: float
    entry_factor: float
    marked_value: float = 0.0


def build_trade_stream(
    universe: tuple[PricedSeries, ...],
    *,
    spec: RuleSpec,
    st_timeline: dict[str, tuple[np.ndarray, np.ndarray]],
    pit_root: Path,
    calendar_index: dict[int, int],
    start_date: int,
    end_date: int,
) -> tuple[TradeE, ...]:
    """Every mechanical trade candidate E's gating produces, all cohorts.

    Mirrors evaluate_window's constraint-prefetch fixed point so the stream
    is gated by exactly the same limit knowledge as the published run; the
    portfolio layer then only chooses take-or-skip per signal. Stream trades
    carry prices, not money: costs are re-derived on real notionals at fill
    time by `run_portfolio`.
    """

    touched = _touched_dates_with_buffer(
        universe,
        spec=spec,
        start_date=start_date,
        end_date=end_date,
        st_timeline=st_timeline,
    )
    limits = load_constraints(pit_root, touched)
    for _ in range(MAX_PREFETCH_REFINE_PASSES):
        refined = _touched_dates_with_buffer(
            universe,
            spec=spec,
            start_date=start_date,
            end_date=end_date,
            st_timeline=st_timeline,
            limits=limits,
        )
        if refined <= touched:
            break
        touched |= refined
        limits = load_constraints(pit_root, touched)

    stream: list[TradeE] = []
    for item in universe:
        features = compute_features(item.adjusted_closes, spec)
        st_mask = build_st_mask(item.dates, item.code, st_timeline)
        trades, _counts = simulate_trades_e(
            item,
            features,
            entry_signal=features.entry_signal & ~st_mask,
            start_date=start_date,
            end_date=end_date,
            limits=limits,
            calendar_index=calendar_index,
            costs=CostModel(),
        )
        stream.extend(trades)
    stream.sort(key=lambda t: (t.entry_signal_date, t.code))
    return tuple(stream)


def _buy_cost(shares: float, raw_price: float, costs: CostModel) -> float:
    notional = shares * raw_price
    commission = max(costs.commission_rate * notional, costs.min_commission)
    return (
        notional
        + commission
        + costs.transfer_fee_rate * notional
        + costs.slippage_rate * notional
    )


def _sell_proceeds(shares: float, raw_price: float, costs: CostModel) -> float:
    notional = shares * raw_price
    commission = max(costs.commission_rate * notional, costs.min_commission)
    return (
        notional
        - commission
        - costs.transfer_fee_rate * notional
        - costs.stamp_duty_rate * notional
        - costs.slippage_rate * notional
    )


def run_portfolio(
    stream: tuple[TradeE, ...],
    series_by_code: dict[str, PricedSeries],
    calendar: tuple[str, ...],
    *,
    start_date: int,
    end_date: int,
    config: PortfolioConfig = PortfolioConfig(),
    costs: CostModel = CostModel(),
) -> dict[str, object]:
    """Deterministic capital replay over one window. See module docstring."""

    cash = config.initial_capital
    positions: dict[str, _OpenPosition] = {}
    # One pending entry per code at most: the duplicate check below makes a
    # second decision for the same code impossible while one is in flight.
    pending: dict[str, TradeE] = {}
    dropped = {
        "slots_full": 0,
        "duplicate_or_pending_security": 0,
        "exposure_cap": 0,
        "insufficient_cash_at_fill": 0,
    }
    taken = 0
    equity_curve: list[float] = []

    window_days = [int(day) for day in calendar if start_date <= int(day) <= end_date]
    by_entry_day: dict[int, list[TradeE]] = {}
    by_decision_day: dict[int, list[TradeE]] = {}
    # Exits are registered when the entry actually fills, never from the
    # raw stream: a skipped signal's exit date must not close a position
    # that a different, later signal of the same security opened.
    by_exit_day: dict[int, list[TradeE]] = {}
    for trade in stream:
        by_entry_day.setdefault(trade.entry_date, []).append(trade)
        by_decision_day.setdefault(trade.entry_signal_date, []).append(trade)

    def _mark(position: _OpenPosition, day: int) -> float:
        item = series_by_code[position.code]
        index = int(np.searchsorted(item.dates, day, side="right")) - 1
        if index < 0:
            return position.marked_value
        raw_close = float(item.closes[index])
        factor = float(item.adjusted_closes[index]) / raw_close
        # Economic mark-to-market across corporate actions: value scales by
        # the adjustment-factor ratio between today and the entry bar.
        position.marked_value = (
            position.shares * raw_close * factor / position.entry_factor
        )
        return position.marked_value

    def _held_value(day: int) -> float:
        return sum(_mark(p, day) for p in positions.values())

    def _decide(day: int) -> None:
        nonlocal taken
        held_value = _held_value(day)
        equity = cash + held_value
        for trade in by_decision_day.get(day, ()):
            if trade.code in positions or trade.code in pending:
                dropped["duplicate_or_pending_security"] += 1
                continue
            if len(positions) + len(pending) >= config.max_positions:
                dropped["slots_full"] += 1
                continue
            target = config.position_fraction * equity
            pending_committed = config.position_fraction * len(pending) * equity
            if (
                held_value + pending_committed + target
                > (config.total_exposure_cap + EXPOSURE_TOLERANCE) * equity
            ):
                dropped["exposure_cap"] += 1
                continue
            pending[trade.code] = trade
            taken += 1

    for day in window_days:
        for code, trade in list(pending.items()):
            if trade.entry_date != day:
                continue
            del pending[code]
            item = series_by_code[code]
            raw_open = float(item.opens[trade.entry_index])
            entry_factor = float(item.adjusted_opens[trade.entry_index]) / raw_open
            target = config.position_fraction * (cash + _held_value(day))
            shares = target / raw_open
            cost = _buy_cost(shares, raw_open, costs)
            if cost > cash:
                dropped["insufficient_cash_at_fill"] += 1
                continue
            cash -= cost
            positions[code] = _OpenPosition(
                code=code, shares=shares, entry_factor=entry_factor
            )
            if trade.status == "closed":
                by_exit_day.setdefault(trade.exit_date, []).append(trade)
        for trade in by_exit_day.get(day, ()):
            position = positions.pop(trade.code, None)
            if position is None:
                continue
            item = series_by_code[trade.code]
            cash += _sell_proceeds(
                position.shares, float(item.opens[trade.exit_index]), costs
            )
        _decide(day)
        equity_curve.append(cash + _held_value(day))

    open_value = sum(_mark(p, window_days[-1]) for p in positions.values())
    return {
        "equity_curve": equity_curve,
        "trades_taken": taken,
        "dropped": dropped,
        "open_at_window_end": {
            "count": len(positions),
            "marked_value": open_value,
        },
    }


def _curve_metrics(
    equity_curve: list[float], config: PortfolioConfig
) -> dict[str, float | int | None]:
    start = equity_curve[0]
    end = equity_curve[-1]
    returns = np.diff(equity_curve) / np.asarray(equity_curve[:-1])
    peak = np.maximum.accumulate(np.asarray(equity_curve))
    drawdowns = 1.0 - np.asarray(equity_curve) / peak
    std = float(np.std(returns)) if len(returns) else 0.0
    years = len(equity_curve) / config.trading_days_per_year
    return {
        "days": len(equity_curve),
        "total_return_pct": (end / start - 1.0) * 100.0,
        "annualized_return_pct": ((end / start) ** (1.0 / years) - 1.0) * 100.0
        if years > 0
        else None,
        "max_drawdown_pct": float(drawdowns.max()) * 100.0,
        "sharpe_rf0_daily_annualized": (
            float(np.mean(returns)) / std * math.sqrt(config.trading_days_per_year)
            if std > 0
            else None
        ),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pit-root", type=Path, default=Path("data/marketdata_pit"))
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH)
    args = parser.parse_args(argv)

    calendar = load_trade_dates(args.pit_root)
    calendar_index = {int(day): i for i, day in enumerate(calendar)}
    series, coverage = load_priced_panel(
        args.pit_root,
        start_date=PREREGISTERED_START_DATE,
        end_date=PREREGISTERED_END_DATE,
    )
    universe, universe_report = build_universe(series)
    series_by_code = {item.code: item for item in universe}
    st_timeline = load_st_timeline(args.pit_root)
    spec = RuleSpec(stop_days=PREREGISTERED_STOP_DAYS)
    config = PortfolioConfig()
    # Actual broker fees per owner 2026-08-22 (prereg section 1).
    costs = CostModel(commission_rate=0.00015)

    oos_start = int(next(d for d in calendar if d > PREREGISTERED_SPLIT_DATE))
    windows_spec = {
        "in_sample": (int(PREREGISTERED_START_DATE), int(PREREGISTERED_SPLIT_DATE)),
        "out_of_sample": (oos_start, int(PREREGISTERED_END_DATE)),
    }

    windows: dict[str, object] = {}
    judgments: dict[str, bool | None] = {}
    for name, (start, end) in windows_spec.items():
        stream = build_trade_stream(
            universe,
            spec=spec,
            st_timeline=st_timeline,
            pit_root=args.pit_root,
            calendar_index=calendar_index,
            start_date=start,
            end_date=end,
        )
        cohort_counts = {
            "all": len(stream),
            "closed_primary": sum(
                1 for t in stream if t.status == "closed" and t.cohort == "primary"
            ),
            "closed_disclosure_only": sum(
                1
                for t in stream
                if t.status == "closed" and t.cohort == "disclosure_only"
            ),
            "flagged_unverified_fill": sum(
                1 for t in stream if t.cohort == "flagged_unverified_fill"
            ),
            "open_or_unresolved": sum(1 for t in stream if t.status != "closed"),
        }
        main_curve = run_portfolio(
            stream,
            series_by_code,
            calendar,
            start_date=start,
            end_date=end,
            config=config,
            costs=costs,
        )
        # Post-hoc attribution disclosure (prereg section 3): filtering by a
        # label that only exists after each exit is look-ahead by design and
        # is reported as such, never as an executable alternative.
        primary_stream = tuple(
            t for t in stream if t.status == "closed" and t.cohort == "primary"
        )
        attribution_curve = run_portfolio(
            primary_stream,
            series_by_code,
            calendar,
            start_date=start,
            end_date=end,
            config=config,
            costs=costs,
        )
        main_metrics = _curve_metrics(main_curve["equity_curve"], config)
        judgments[name] = (
            main_metrics["annualized_return_pct"] > 0
            if name == "out_of_sample"
            else None
        )
        windows[name] = {
            "stream_cohort_counts": cohort_counts,
            "main_curve_all_signals": {
                "metrics": main_metrics,
                "trades_taken": main_curve["trades_taken"],
                "dropped": main_curve["dropped"],
                "open_at_window_end": main_curve["open_at_window_end"],
            },
            "primary_attribution_disclosure_post_hoc": {
                "metrics": _curve_metrics(
                    attribution_curve["equity_curve"], config
                ),
                "trades_taken": attribution_curve["trades_taken"],
                "dropped": attribution_curve["dropped"],
            },
        }

    report = {
        "study": "m3-520-portfolio-validation",
        "preregistration": PREREGISTRATION,
        "config": {
            "initial_capital_cny": config.initial_capital,
            "total_exposure_cap": config.total_exposure_cap,
            "max_positions": config.max_positions,
            "position_fraction": config.position_fraction,
            "researcher_added": [
                "initial_capital",
                "max_positions",
                "position_fraction",
            ],
            "owner_authorized": ["total_exposure_cap (cross-card citation)"],
        },
        "cost_model": {
            "commission_rate": costs.commission_rate,
            "min_commission": costs.min_commission,
            "transfer_fee_rate": costs.transfer_fee_rate,
            "stamp_duty_rate": costs.stamp_duty_rate,
            "slippage_rate": costs.slippage_rate,
        },
        "criteria_note": (
            "necessary condition only: out-of-sample main-curve annualized "
            "net return > 0; drawdown carries no threshold by design; no "
            "portfolio placebo (prereg sections 4-5)"
        ),
        "judgment_oos_main_curve_annualized_positive": judgments["out_of_sample"],
        "pit_disclaimer": (
            "single terminal-vintage reconstruction truncated by trade_date; "
            "algorithm-layer as-of only, knowledge-time PIT not provable"
        ),
        "panel_load": coverage,
        "universe": universe_report,
        "windows": windows,
        "real_broker_orders": False,
    }
    args.output.write_text(
        json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    summary = {
        name: {
            "main_metrics": block["main_curve_all_signals"]["metrics"],
            "taken": block["main_curve_all_signals"]["trades_taken"],
            "dropped": block["main_curve_all_signals"]["dropped"],
        }
        for name, block in windows.items()
    }
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    print("written:", args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
